### ISSUE TITLE
Cannot find headers/buffer.h

### ISSUE THREAD

**Issue by Li-Pin-Hsueh** [amiq-consulting/CNN-using-HLS#2]
Hi, when I want to run C synthesis. It has error:
*********************************************************************
WARNING: [HLS 200-40] CNN-using-HLS/modules/conv/conv.cpp:23:10: fatal error: 'headers/buffer.h' file not found
#include "headers/buffer.h"
         ^
1 error generated.
C preprocessor failed.
    while executing
"source C:/Users/Aaron/Desktop/nnet_project/solution1/csynth.tcl"
    invoked from within
"hls::main C:/Users/Aaron/Desktop/nnet_project/solution1/csynth.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 hls::main {*}$args"
    (procedure "hls_proc" line 5)
    invoked from within
"hls_proc $argv"
*******************************************************************

Any suggestion?

**Comment by amiq-consulting** [comment]
Hi Chang,

Indeed I have missed a file in that project. I have added it and now and it is on github. You can pull the latest version of the repo,

Thank you for pointing this out!
Sergiu
