### ISSUE TITLE
File get_params.py is failed

### ISSUE THREAD

**Issue by Ultrasq** [amiq-consulting/CNN-using-HLS#4]
Hello, Sergiu

File get_params.py have error in 119 line.
 
mini_batch_X = **shufpytfled**_X[:,  mini_batch_size * k: mini_batch_size* (k+1)]
       
 mini_batch_X = **shuffled_X**[:,  mini_batch_size * k: mini_batch_size* (k+1)]

**Comment by amiq-consulting** [comment]
Fixed. It was a typo
